---
title: "Basics of Data visualization"
author: "Ugyen Norbu"
output:
  html_document: default
  pdf_document: default
---

```{r fig.width = 5, fig.height = 3.5, warning=FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
library(socviz)
library(gapminder)

gapminder %>% 
    ggplot(aes(x = gdpPercap, y = lifeExp)) +
    geom_point(alpha = 0.15) +
    geom_smooth(color = "orange", method = "lm") +
    scale_x_log10(labels= scales::comma)

ggsave("output_fig/gdp_lifeexp.jpg")
```


```{r warning=FALSE, echo=FALSE, message=FALSE}
gapminder %>% 
    ggplot(aes(x = gdpPercap, y = lifeExp, color = continent,
               fill = continent)) +
    geom_point(alpha = 0.25) +
    geom_smooth(method = "loess") +
    scale_x_log10(labels= scales::comma)

ggsave("output_fig/gdp_lifeexp_2.jpg")

gapminder %>% 
  ggplot(aes(x = year, y = gdpPercap)) +
  geom_line(aes(group = country), color ="#BDBDBD") +
  facet_wrap(facets = "continent", ncol = 5) +
  geom_smooth(method = "loess", se = FALSE, color = c("#EE9A00")) +
  scale_y_log10(labels = scales::comma)
```
```{r warning=FALSE, echo=FALSE, message=FALSE}
gss_sm %>% 
  ggplot(aes(x = age, y = childs)) +
  geom_point(color ="#BDBDBD") +
  facet_grid(sex ~ race) +
  geom_smooth(method = "loess", se = FALSE, color = c("#EE9A00"))
```

```{r warning=FALSE, echo=FALSE, message=FALSE}
gss_sm %>% 
  ggplot(aes(x = bigregion)) +
  geom_bar(aes(y = ..prop.., group = 1))
```
```{r warning=FALSE, echo=FALSE, message=FALSE}
table(gss_sm$religion)

gss_sm%>% 
  ggplot(aes(x =bigregion, fill = religion))+
  geom_bar(position = "fill") +
  guides(fill = FALSE)
```
```{r warning=FALSE, echo=FALSE, message=FALSE}
gss_sm %>%
  ggplot(aes(x =bigregion, fill = religion))+
  geom_bar(position = "dodge", aes(y = ..prop.., group = religion))
```
```{r warning=FALSE, echo=FALSE, message=FALSE}
midwest %>% 
  ggplot(aes(x = area)) +
  geom_histogram(bins = 20) +
  geom_density()
```
```{r warning=FALSE, echo=FALSE, message=FALSE}
oecd_sum %>% 
  ggplot(aes(x = year, y= diff, fill = hi_lo)) +
  geom_bar(stat = "identity") +
  guides(fill = FALSE)
```

```{r error=FALSE, warning=FALSE, echo=FALSE}
rel_by_region <- gss_sm %>% 
  group_by(bigregion, religion) %>% 
  summarise(N = n()) %>% 
  mutate(freq = N/sum(N), per = round(freq*100, 0))
```

```{r error=FALSE, warning=FALSE, echo=FALSE}
rel_by_region %>% 
  ggplot(aes(x = bigregion, y = per, fill = religion)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(facets = "religion") +
  coord_flip()+
  guides(fill = FALSE)
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
organdata %>% 
  select(1:6) %>% 
  sample_n(size = 10)

organdata %>% 
  ggplot(aes(x = year, y = donors))+
  geom_line(aes(group = country))+
  facet_wrap(facets = "country")

```

```{r error=FALSE, warning=FALSE, echo=FALSE}
organdata %>% 
  ggplot(aes(x = reorder(country, -donors, na.rm = TRUE),
             y = donors))+
  geom_boxplot()+
  coord_flip()
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
by_country <- organdata %>% 
  group_by(consent_law, country) %>% 
  summarise_if(is.numeric, list(avg = mean, sd = sd), na.rm = TRUE) %>%
  ungroup()

by_country %>% 
  ggplot(aes(x = donors_avg, y = reorder(country, donors_avg)))+
  geom_point(aes(color = consent_law))+
  facet_wrap(facet = "consent_law", scales = "free_y", ncol = 1)+
  guides(color = FALSE)
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
by_country %>% 
  ggplot(aes(x = reorder(country, -donors_avg), y = donors_avg)) +
  geom_pointrange(aes(ymin = donors_avg - donors_sd, 
                      ymax = donors_avg + donors_sd))+
  coord_flip()
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
library(ggrepel)

elections_historic %>% 
  ggplot(aes(x = popular_pct, y = ec_pct, label = winner_label))+
  geom_vline(xintercept = 0.5)+
  geom_hline(yintercept = 0.5)+
  geom_point() +
  geom_text_repel()+
  scale_x_continuous(labels = scales::percent)+
  scale_y_continuous(labels = scales::percent)
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
by_country %>% 
  ggplot(aes(x = gdp_avg, y = health_avg))+
  geom_point()+
  geom_text_repel(data = subset(by_country, gdp_avg >25000|country %in% ("Belgium")), aes(label = country))
```

```{r error=FALSE, warning=FALSE, echo=FALSE}
organdata
organdata %>% 
  ggplot(aes(x = roads, y = donors)) +
  geom_point() +
  annotate(geom = "text", x = 100, y = 30,
           label = "A surprisingly high \n recovery rate.", 
           hjust = 0)
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
organdata %>% 
  ggplot(aes(x = roads, y = donors)) +
  geom_point() +
  xlim(0, 300) +
  annotate(geom = "rect", xmin = 40, xmax = 130,
           ymin = 27, ymax = 33, alpha = 0.5, fill = c("#B0E2FF"))+
  annotate(geom = "text", x = 50, y = 30,
           label = "A surprisingly high \n recovery rate.", color = c("#1874CD"),
           hjust = 0)
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
library(hrbrthemes)

organdata %>% 
  ggplot(aes(x = roads, y = donors, color = world)) +
  geom_point() +
  scale_x_log10() +
  scale_y_continuous(breaks = c(10, 20, 30),
                     labels = c("Ten", "Twenty", "Thirty")) +
  guides(color = "none") +
  theme_ipsum()
  
```
```{r error=FALSE, warning=FALSE, echo=FALSE}
organdata %>% 
  ggplot(aes(x = roads, y = donors, color = world)) +
  geom_point() +
  theme(legend.position = "top")
```